### ISSUE TITLE
Admin(Menu) : Second level submenu is getting distorted

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Laboratory-Analysers#23]
![1](https://cloud.githubusercontent.com/assets/13309806/13067155/1ad4f952-d422-11e5-9434-0aafe798ff9c.png)

**Comment by ravi-josyula** [comment]
![2016-02-24_1129](https://cloud.githubusercontent.com/assets/13309806/13276899/ef58f03e-dae9-11e5-9348-1d9571329cef.png)

**Comment by nakul-titan** [comment]
With reference to the task # 5 in  project scope document only  2 level of sub-menus have been implemented.
