### ISSUE TITLE
Admin(Inner pages ) Banner Background image : ACF image field is not implemented

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Laboratory-Analysers#27]
![6](https://cloud.githubusercontent.com/assets/13309806/13068183/9ff7cbc2-d42d-11e5-8e78-9200cc6df934.png)

**Comment by nakul-titan** [comment]
Only default image should come from Titan Options and rest of images can be added in their respective pages.

**Comment by ravi-josyula** [comment]
Banner image is not displaying for all inner pages, except Profiles page
