### ISSUE TITLE
Admin: Enquire today page link: There is no option to hide the button

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Laboratory-Analysers#41]
- Enquire Today:
    - ACF Text field to customise the button label
    - ACF Page link field to link button to a Page / Post
    - **Hide button if page link is not set**

![5](https://cloud.githubusercontent.com/assets/13309806/13068915/c4c1712c-d434-11e5-8fbe-37b1397ff9ff.png)

**Comment by nakul-titan** [comment]
As per scope button should be hidden if page link is not available and it has to implement in code not in backend.
