### ISSUE TITLE
General: Letters in the ordered list are replaced with numbers.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Laboratory-Analysers#67]
![image](https://cloud.githubusercontent.com/assets/11186313/13734927/0fc66da8-e9de-11e5-82b6-ad1c1b8ad1ad.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/13912204/9c183e16-ef75-11e5-8594-b6b3230381d0.png)

**Comment by nakul-titan** [comment]
![alphabets](https://cloud.githubusercontent.com/assets/13461911/13915168/fc048aca-ef78-11e5-88be-1c354800018f.png)

**Comment by nakul-titan** [comment]
New ordered list is starting from second point
