### ISSUE TITLE
Product listing: Clipped part of the product title is still visible.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Laboratory-Analysers#68]
![image](https://cloud.githubusercontent.com/assets/11186313/13734953/86c25728-e9de-11e5-816d-0b356fd98dbe.png)

**Comment by roseliesromeo** [comment]
![image](https://cloud.githubusercontent.com/assets/11186313/13912198/8d70cba8-ef75-11e5-9090-8910e5380e05.png)

**Comment by nakul-titan** [comment]
Hi it is working fine
Thank you
![product category page](https://cloud.githubusercontent.com/assets/13461911/13945655/0645e346-f035-11e5-8d11-6b485f9c522b.png)
