### ISSUE TITLE
Mobile - home - our products: Other products are cut.  It should display and one product per slide.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Laboratory-Analysers#77]
Image should resize and fit in the screen.
![image](https://cloud.githubusercontent.com/assets/11186313/13736187/541418b6-e9ed-11e5-8ced-57381c244ed9.png)

**Comment by nakul-titan** [comment]
Title width issue has been resolved and as per design some part of other products should be visible.
