### ISSUE TITLE
Mobile - home - lead ins: Lead-ins are not displayed in mobile view.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Laboratory-Analysers#78]
Beginning with 1199 resolution and below.

**Comment by nakul-titan** [comment]
As it is very difficult to adjust the leading shapes and design for small screens it is intentionally made hidden for mobile and tablet devices.

**Comment by roseliesromeo** [comment]
In mobile view, you don't have to follow the shape.  Layout may not be followed for as long as the elements are there.

**Comment by nakul-titan** [comment]
in order to show the lead-ins in mobile devices we have to decrease the font-size to very small extent, which in no longer readable, hence the lead-ins are restricted to show till tablet devices.

**Comment by roseliesromeo** [comment]
In devices with smaller resolution, you can display the items below the banner.  You may not follow the exact layout as long as the exact elements are visible.
Per standards:
https://knowledgebase.titanweb.com.au/implementation/mobile-and-browsers/lead-ins-and-cta
or you may refer to this site
http://thesamaritans.stage.titanweb.com.au/
