### ISSUE TITLE
General - pages: There is Background Banner Image in every page but not working.  It will still take the featured image as the banner image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Laboratory-Analysers#82]
![image](https://cloud.githubusercontent.com/assets/11186313/13736542/4ba38088-e9f0-11e5-8b8f-8bc0c5940b8a.png)

**Comment by nakul-titan** [comment]
Hi, I have added a testing page and uploaded banner image it is working fine. If no background Image is available then it will display default image.

**Comment by roseliesromeo** [comment]
It is still not working.  
![image](https://cloud.githubusercontent.com/assets/11186313/13911769/a1b0155c-ef6f-11e5-807d-a53923449e2b.png)
I also checked the link above, banner image won't display as well.
![image](https://cloud.githubusercontent.com/assets/11186313/13911803/27316d8e-ef70-11e5-8e19-704fdc4317ad.png)

**Comment by nakul-titan** [comment]
Hi
Since the field added was banner image, so image will appear as banner image not the featured image, i have added the image and it is working fine.
Thanks.
![banner image test](https://cloud.githubusercontent.com/assets/13461911/13945503/df7ae118-f033-11e5-9026-dfe70618fa61.png)
